// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         licenseKey: "DS5D2368HCME4O9X",
 *         printerIp: "192.168.1.50",
 *         displayName: "Cocina",
 *         widthMm: 80,
 *         source: "windows",
 *         sourceId: "POS-01"
 *     }
 */
export interface CreatePrinterRequest {
    /** License key (16 caracteres) del punto de venta al que pertenece la impresora. */
    licenseKey: string | null;
    /** Dirección IP de la impresora en la red local de la sucursal (p. ej. "192.168.1.50"). */
    printerIp: string | null;
    /** Nombre visible de la impresora (p. ej. "Cocina", "Barra"). */
    displayName?: string | null;
    /** Ancho del papel en milímetros (típicamente 58 u 80). */
    widthMm: number;
    /** Origen opcional de la impresora cuando se importa de un sistema externo. */
    source?: string | null;
    /** Identificador de la impresora en el sistema de origen, si aplica. */
    sourceId?: string | null;
}
