// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../../../../index.js";

/**
 * @example
 *     {
 *         licenseKey: "licenseKey",
 *         orderFolio: "169",
 *         isReprint: false,
 *         price: 128.5,
 *         paymentMethod: "CARD",
 *         businessName: "Mi Restaurante",
 *         businessSubtitle: "Sucursal Centro",
 *         groups: [{
 *                 printerId: "00000000-b12a-405f-905d-dbf424c20000",
 *                 jobType: "order",
 *                 title: "COCINA",
 *                 items: [{
 *                         idProduct: "01052",
 *                         name: "Hamburguesa doble carne",
 *                         quantity: 2,
 *                         price: 89,
 *                         modifiers: [{
 *                                 idModifier: "50110",
 *                                 name: "Sin cebolla",
 *                                 price: 0
 *                             }],
 *                         notes: "Sin pepinillos"
 *                     }]
 *             }]
 *     }
 */
export interface PrintOrderRequest {
    licenseKey: string;
    /** Folio de la orden mostrado en el ticket (p. ej. "169"). */
    orderFolio: string | null;
    /** Indica si el ticket ya había sido impreso anteriormente. */
    isReprint: boolean;
    /** Total de la orden. Se guarda para futuras plantillas de recibo; no se imprime en la comanda. */
    price?: number | null;
    /** Método de pago. Se guarda para futuras plantillas de recibo; no se imprime en la comanda. */
    paymentMethod?: string | null;
    /** Nombre del negocio impreso como encabezado del ticket. */
    businessName?: string | null;
    /** Segunda línea opcional del encabezado, debajo del nombre del negocio (p. ej. marca o sucursal). */
    businessSubtitle?: string | null;
    /** Un grupo de impresión por cada impresora destino. */
    groups: WrestaurantApi.PrintGroupRequest[] | null;
}
