// This file was auto-generated by Fern from our API Definition.

export interface EmpresaDto {
    idEmpresa?: (string | null) | undefined;
    nombre?: (string | null) | undefined;
    razonSocial?: (string | null) | undefined;
    direccion?: (string | null) | undefined;
    sucursal?: (string | null) | undefined;
    rfc?: (string | null) | undefined;
    curp?: (string | null) | undefined;
    telefono?: (string | null) | undefined;
    giro?: (string | null) | undefined;
    contacto?: (string | null) | undefined;
    fax?: (string | null) | undefined;
    email?: (string | null) | undefined;
    fechaCompra?: (string | null) | undefined;
    distribuidor?: (string | null) | undefined;
    numeroFactura?: (string | null) | undefined;
    numeroDeControl?: (string | null) | undefined;
    contrasenaControl?: (string | null) | undefined;
    idHardware?: (string | null) | undefined;
    licenciaPrincipal?: (string | null) | undefined;
    licenciaMonederoElectronico?: (string | null) | undefined;
    licenciaMonitorProduccion?: (string | null) | undefined;
    licenciaSrMovil?: (string | null) | undefined;
    licenciaManttoVentas?: (string | null) | undefined;
    licenciaPagoEnLinea?: (string | null) | undefined;
    licenciaHuellaDigital?: (string | null) | undefined;
    licenciaBillar?: (string | null) | undefined;
    franquicia?: (string | null) | undefined;
    web?: (string | null) | undefined;
    ciudad?: (string | null) | undefined;
    estado?: (string | null) | undefined;
    pais?: (string | null) | undefined;
    ciudadSucursal?: (string | null) | undefined;
    estadoSucursal?: (string | null) | undefined;
    passwordEmpresa?: (string | null) | undefined;
}
