// This file was auto-generated by Fern from our API Definition.

export interface GruposModificadorDto {
    idProducto?: (string | null) | undefined;
    idGruposModificadores?: (string | null) | undefined;
    descripcion?: (string | null) | undefined;
    prioridad?: number | undefined;
    forzarCaptura?: boolean | undefined;
    maximoModificadores?: number | undefined;
    incluidos?: number | undefined;
}
