// This file was auto-generated by Fern from our API Definition.

export interface GrupoDto {
    idGrupo?: (string | null) | undefined;
    descripcion?: (string | null) | undefined;
    clasificacion?: (string | null) | undefined;
    prioridad?: number | undefined;
    color?: (string | null) | undefined;
    colorLetra?: (string | null) | undefined;
    prioridadImpresion?: number | undefined;
    cambiaColorCuenta?: boolean | undefined;
    colorCuenta?: (string | null) | undefined;
    colorLetraCuenta?: (string | null) | undefined;
    solicitaAutorizacion?: boolean | undefined;
    imagenMenuElectronico?: (string | null) | undefined;
    extMenu?: (string | null) | undefined;
    porcentajePropina?: number | undefined;
    imagenMenu?: (string | null) | undefined;
    idEtiqueta?: (number | null) | undefined;
    workspaceId?: (number | null) | undefined;
    alcohol?: boolean | undefined;
    serviceCode?: (string | null) | undefined;
}
