// This file was auto-generated by Fern from our API Definition.

export interface ImpuestosDto {
    nombreImpuesto1?: (string | null) | undefined;
    impuesto1?: number | undefined;
    nombreImpuesto2?: (string | null) | undefined;
    impuesto2?: number | undefined;
    nombreImpuesto3?: (string | null) | undefined;
    impuesto3?: number | undefined;
}
