// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

export interface MeserosResponse {
    workerId?: string | undefined;
    dispatchedAt?: string | undefined;
    totalResults?: number | undefined;
    meseros?: (WrestaurantApi.MeseroDto[] | null) | undefined;
}
