// This file was auto-generated by Fern from our API Definition.

export interface MeseroDto {
    idMeseroInterno?: number | undefined;
    idMesero?: (string | null) | undefined;
    nombre?: (string | null) | undefined;
    contrasena?: (string | null) | undefined;
    tipo?: (number | null) | undefined;
    fotografia?: (string | null) | undefined;
    visible?: boolean | undefined;
    idEmpresa?: (string | null) | undefined;
    tipoAcceso?: boolean | undefined;
    capturaRestringidaMesas?: boolean | undefined;
    perfil?: (string | null) | undefined;
    monitorMeseroColorFondo?: (number | null) | undefined;
    monitorMeseroColorLetra?: (number | null) | undefined;
    accesoIndicadorMesas?: boolean | undefined;
    turnoAbierto?: boolean | undefined;
    comision?: number | undefined;
    autorizaProductosMenuQr?: boolean | undefined;
    workspaceId?: (string | null) | undefined;
}
