// This file was auto-generated by Fern from our API Definition.

export interface ModificadorDto {
    idProducto?: (string | null) | undefined;
    idModificador?: (string | null) | undefined;
    precio?: number | undefined;
    nombre?: (string | null) | undefined;
    idGruposModificadores?: (string | null) | undefined;
}
