// This file was auto-generated by Fern from our API Definition.

export interface ModifiersPrint {
    /** Id interno del modificador. */
    idModifier: string | null;
    /** Nombre del modificador impreso en el ticket. */
    name: string | null;
    /** Precio del modificador. Se guarda para futuras plantillas de recibo; no se imprime en la comanda. */
    price: number;
}
