// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

export interface OpenOrdersResponse {
    workerId?: string | undefined;
    dispatchedAt?: string | undefined;
    totalResults?: number | undefined;
    orders?: (WrestaurantApi.OpenOrderDto[] | null) | undefined;
}
