// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

export interface OpenOrderDto {
    folio?: number | undefined;
    serieFolio?: (string | null) | undefined;
    numcheque?: number | undefined;
    fecha?: string | undefined;
    cierre?: (string | null) | undefined;
    mesa?: (string | null) | undefined;
    noPersonas?: number | undefined;
    idMesero?: (string | null) | undefined;
    pagado?: boolean | undefined;
    cancelado?: boolean | undefined;
    impreso?: boolean | undefined;
    impresiones?: number | undefined;
    descuento?: number | undefined;
    razonCancelado?: (string | null) | undefined;
    orden?: (string | null) | undefined;
    facturado?: boolean | undefined;
    idTurno?: (number | null) | undefined;
    usuarioCancelo?: (string | null) | undefined;
    comentarioDescuento?: (string | null) | undefined;
    usuarioPago?: (string | null) | undefined;
    totalArticulos?: number | undefined;
    subtotal?: number | undefined;
    subtotalSinImpuestos?: number | undefined;
    total?: number | undefined;
    totalConPropina?: number | undefined;
    efectivo?: number | undefined;
    tarjeta?: number | undefined;
    vales?: number | undefined;
    otros?: number | undefined;
    propina?: number | undefined;
    totalSinDescuento?: number | undefined;
    totalAlimentos?: number | undefined;
    totalBebidas?: number | undefined;
    totalOtros?: number | undefined;
    totalDescuentos?: number | undefined;
    totalCortesias?: number | undefined;
    totalCortesiaAlimentos?: number | undefined;
    nombreMesero?: (string | null) | undefined;
    impuestos?: WrestaurantApi.ImpuestosDto | undefined;
}
