// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

export interface OrderDetailDto {
    folioDet?: number | undefined;
    movimiento?: number | undefined;
    comanda?: (string | null) | undefined;
    cantidad?: number | undefined;
    idProducto?: (string | null) | undefined;
    descuento?: number | undefined;
    precio?: number | undefined;
    precioSinImpuestos?: number | undefined;
    comentario?: (string | null) | undefined;
    tiempo?: (string | null) | undefined;
    mitad?: number | undefined;
    hora?: (string | null) | undefined;
    modificador?: number | undefined;
    idEstacion?: (string | null) | undefined;
    usuarioDescuento?: (string | null) | undefined;
    comentarioDescuento?: (string | null) | undefined;
    idTipoDescuento?: (string | null) | undefined;
    idProductoCompuesto?: (string | null) | undefined;
    productoCompuestoPrincipal?: number | undefined;
    precioCatalogo?: number | undefined;
    marcar?: number | undefined;
    idMeseroProducto?: (string | null) | undefined;
    idCortesia?: (string | null) | undefined;
    numeroTarjeta?: (string | null) | undefined;
    folioProduccion?: number | undefined;
    nivel?: number | undefined;
    sistemaEnvio?: number | undefined;
    promoVolumen?: number | undefined;
    impuestos?: WrestaurantApi.ImpuestosDto | undefined;
}
