// This file was auto-generated by Fern from our API Definition.

export interface OrderPaymentMethodsDto {
    folio?: number | undefined;
    idFormaDePago?: (string | null) | undefined;
    descripcion?: (string | null) | undefined;
    importe?: number | undefined;
    propina?: number | undefined;
    tipoDeCambio?: number | undefined;
}
