// This file was auto-generated by Fern from our API Definition.

export interface PartialProductDto {
    idProducto?: (string | null) | undefined;
    descripcionProducto?: (string | null) | undefined;
    idGrupo?: (string | null) | undefined;
    movimiento?: number | undefined;
    cantidad?: number | undefined;
    descripcionGrupo?: (string | null) | undefined;
    clasificacion?: (string | null) | undefined;
    modificador?: (number | null) | undefined;
    productoCompuestoPrincipal?: number | undefined;
    nombreCorto?: (string | null) | undefined;
    imagen?: (string | null) | undefined;
    visibleMenu?: boolean | undefined;
    idProdServSat?: (string | null) | undefined;
    comentario?: (string | null) | undefined;
    precio?: number | undefined;
    precioSinImpuestos?: number | undefined;
    impuesto1?: number | undefined;
    impuesto2?: number | undefined;
    impuesto3?: number | undefined;
    descuento?: number | undefined;
    bloqueado?: boolean | undefined;
    permitirprodcompenmodif?: boolean | undefined;
}
