// This file was auto-generated by Fern from our API Definition.

export interface PaymentMethodDto {
    idFormaDePago?: (string | null) | undefined;
    descripcion?: (string | null) | undefined;
    tipo?: (number | null) | undefined;
    tipoDeCambio?: (number | null) | undefined;
    solicitaReferencia?: (boolean | null) | undefined;
    prioridadBoton?: (number | null) | undefined;
    cuentaContableImporte?: (string | null) | undefined;
    cuentaContableComision?: (string | null) | undefined;
    cuentaContableIvaComision?: (string | null) | undefined;
    comision?: (number | null) | undefined;
    visible?: (boolean | null) | undefined;
    aceptaPropina?: (boolean | null) | undefined;
    subtipo?: (number | null) | undefined;
    prefijo1?: (string | null) | undefined;
    prefijo2?: (string | null) | undefined;
    codigoDePrefijoconsulta?: (string | null) | undefined;
    codigoDePrefijoacumred?: (string | null) | undefined;
    generaPuntos?: (boolean | null) | undefined;
    formatoImpresion?: (number | null) | undefined;
    idFPagoFiscal?: (number | null) | undefined;
    pagoEnLinea?: (number | null) | undefined;
    tipoTarjeta?: (number | null) | undefined;
    noFacturable?: (boolean | null) | undefined;
    comisionReporte1?: (number | null) | undefined;
    comisionReporte2?: (number | null) | undefined;
    tipoTarjetaBancaria?: number | undefined;
    idTipoDescuento?: (string | null) | undefined;
    idFormaPagoSat?: (string | null) | undefined;
    serviceCode?: (string | null) | undefined;
    leerBrazalete?: boolean | undefined;
    cargoHabitacionEg?: boolean | undefined;
    visibleKiosco?: boolean | undefined;
    autocapturar?: boolean | undefined;
    sumaTotal?: boolean | undefined;
    equivalencia?: (string | null) | undefined;
    bloqueaImporte?: boolean | undefined;
}
