// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

export interface PrintLineRequest {
    /** Id interno del producto. */
    idProduct: string | null;
    /** Nombre del producto impreso en el ticket. */
    name: string | null;
    /** Cantidad solicitada. */
    quantity: number;
    /** Precio unitario. Se guarda para futuras plantillas de recibo; no se imprime en la comanda. */
    price?: (number | null) | undefined;
    /** Modificadores del producto, impresos como líneas "+ {nombre}". */
    modifiers: WrestaurantApi.ModifiersPrint[] | null;
    /** Nota libre para esta línea, impresa como "nota: {notas}". */
    notes?: (string | null) | undefined;
}
