// This file was auto-generated by Fern from our API Definition.

export interface PrintGroupResult {
    /** Id de la impresora a la que apuntó este grupo. */
    printerId?: (string | null) | undefined;
    /** Id de auditoría del trabajo de impresión creado, si se creó alguno. */
    jobId?: (string | null) | undefined;
    /** Estado del resultado: "Completed" o "Failed". */
    status?: (string | null) | undefined;
    /** Detalle de la falla cuando el grupo no se imprimió. */
    error?: (string | null) | undefined;
}
