// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

export interface PrinterAssignmentsResponse {
    workerId?: string | undefined;
    printers?: (WrestaurantApi.PrinterAssignmentDto[] | null) | undefined;
}
