// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

export interface PrintGroupRequest {
    /** Id de la impresora destino (obtenido de GET /print/{licenseKey}/printers). */
    printerId: string | null;
    /** Qué se imprime. Envíe "receipt" para el recibo del cliente o "order" para la comanda de preparación (cocina/barra). */
    jobType: PrintGroupRequest.JobType;
    /** Título del ticket — se imprime como la línea de destino (p. ej. "COCINA"). */
    title: string | null;
    /** Artículos a imprimir en este ticket. */
    items: WrestaurantApi.PrintLineRequest[] | null;
    /** QR del ticket si se requiere. Reservado para la futura plantilla de recibo. */
    qrData?: (string | null) | undefined;
}

export namespace PrintGroupRequest {
    /** Qué se imprime. Envíe "receipt" para el recibo del cliente o "order" para la comanda de preparación (cocina/barra). */
    export const JobType = {
        Receipt: "receipt",
        Order: "order",
    } as const;
    export type JobType = (typeof JobType)[keyof typeof JobType];
}
