// This file was auto-generated by Fern from our API Definition.

/**
 * Impresora a la que el kiosko puede apuntar por su id en una solicitud de impresión.
 */
export interface PrinterAssignmentDto {
    id?: string | undefined;
    printerIp?: (string | null) | undefined;
    displayName?: (string | null) | undefined;
    widthMm?: number | undefined;
    source?: (string | null) | undefined;
}
