// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

/**
 * Resultado de despachar una orden — una entrada por grupo de impresión, con resultados independientes.
 */
export interface PrintOrderResponse {
    orderRef?: (string | null) | undefined;
    results?: (WrestaurantApi.PrintGroupResult[] | null) | undefined;
}
