// This file was auto-generated by Fern from our API Definition.

/**
 * Impresora que pertenece a un cliente, vinculada a uno de sus puntos de venta.
 */
export interface PrinterDto {
    id?: string | undefined;
    workerId?: string | undefined;
    licenseKey?: (string | null) | undefined;
    printerIp?: (string | null) | undefined;
    displayName?: (string | null) | undefined;
    widthMm?: number | undefined;
    source?: (string | null) | undefined;
    sourceId?: (string | null) | undefined;
    createdAt?: string | undefined;
    updatedAt?: string | undefined;
}
