// This file was auto-generated by Fern from our API Definition.

export interface ProblemDetails {
    type?: (string | null) | undefined;
    title?: (string | null) | undefined;
    status?: (number | null) | undefined;
    detail?: (string | null) | undefined;
    instance?: (string | null) | undefined;
    /** Accepts any additional properties */
    [key: string]: any;
}
