// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

export interface ProductDto {
    idProducto?: (string | null) | undefined;
    descripcionProducto?: (string | null) | undefined;
    idGrupo?: (string | null) | undefined;
    descripcionGrupo?: (string | null) | undefined;
    clasificacion?: (string | null) | undefined;
    nombreCorto?: (string | null) | undefined;
    imagen?: (string | null) | undefined;
    visibleMenu?: boolean | undefined;
    idProdServSat?: (string | null) | undefined;
    precio?: number | undefined;
    precioSinImpuestos?: number | undefined;
    impuesto1?: number | undefined;
    impuesto2?: number | undefined;
    impuesto3?: number | undefined;
    bloqueado?: boolean | undefined;
    permitirprodcompenmodif?: boolean | undefined;
    modificadores?: (WrestaurantApi.ModificadorDto[] | null) | undefined;
    gruposModificadores?: (WrestaurantApi.GruposModificadorDto[] | null) | undefined;
    comentarios?: (WrestaurantApi.CommentDto[] | null) | undefined;
}
