// This file was auto-generated by Fern from our API Definition.

export interface StationDto {
    idEstacion?: (string | null) | undefined;
    descripcion?: (string | null) | undefined;
    serie?: (string | null) | undefined;
    ip?: (string | null) | undefined;
    impresoraCheques?: (string | null) | undefined;
    impresoraNotas?: (string | null) | undefined;
    cajaComandero?: (string | null) | undefined;
    directorioRespaldo?: (string | null) | undefined;
    rutaTemporal?: (string | null) | undefined;
}
