// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../index.js";

export interface StationsQueryResponse {
    jobId?: string | undefined;
    workerId?: string | undefined;
    dispatchedAt?: string | undefined;
    page?: number | undefined;
    pageSize?: number | undefined;
    totalResults?: number | undefined;
    totalPages?: number | undefined;
    hasNextPage?: boolean | undefined;
    stations?: (WrestaurantApi.StationDto[] | null) | undefined;
}
