// This file was auto-generated by Fern from our API Definition.

export interface TurnoDto {
    idTurnoInterno?: number | undefined;
    idTurno?: number | undefined;
    fondo?: number | undefined;
    apertura?: (string | null) | undefined;
    cierre?: (string | null) | undefined;
    idEstacion?: (string | null) | undefined;
    cajero?: (string | null) | undefined;
    efectivo?: number | undefined;
    tarjeta?: number | undefined;
    vales?: number | undefined;
    credito?: number | undefined;
    procesadoWeb?: boolean | undefined;
    idEmpresa?: (string | null) | undefined;
    enviadoACentral?: boolean | undefined;
    fechaEnviado?: (string | null) | undefined;
    usuarioEnvio?: (string | null) | undefined;
    offline?: boolean | undefined;
    enviadoAf?: boolean | undefined;
    corteEnviado?: boolean | undefined;
    eliminarTemporalesEnCierre?: boolean | undefined;
    idMesero?: (string | null) | undefined;
    fondoDolares?: number | undefined;
    procesado?: boolean | undefined;
}
