// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../../../../index.js";

/**
 * @example
 *     {
 *         licenseKey: "licenseKey"
 *     }
 */
export interface CreateClosedOrderRequest {
    licenseKey: string;
    "Idempotency-Key"?: string;
    turnDependent?: boolean;
    estacion?: string | null;
    serie?: string | null;
    idEmpresa?: string | null;
    noPersonas?: number;
    productos?: WrestaurantApi.PartialProductDto[] | null;
    idFormaDePago?: string | null;
}
