// This file was auto-generated by Fern from our API Definition.

import type * as WrestaurantApi from "../../../../index.js";

/**
 * @example
 *     {
 *         licenseKey: "licenseKey",
 *         turnDependent: true,
 *         mesa: "5",
 *         idMesero: "001",
 *         estacion: "CAJA1",
 *         serie: "A",
 *         idEmpresa: "1",
 *         noPersonas: 2,
 *         productos: [{
 *                 idProducto: "01052",
 *                 descripcionProducto: "Hamburguesa doble carne",
 *                 idGrupo: "0007",
 *                 movimiento: 1,
 *                 cantidad: 2,
 *                 descripcionGrupo: "Hamburguesas",
 *                 clasificacion: "ALIMENTOS",
 *                 productoCompuestoPrincipal: 0,
 *                 nombreCorto: "Hamb. doble",
 *                 imagen: "",
 *                 visibleMenu: true,
 *                 idProdServSat: "50202306",
 *                 comentario: "Sin pepinillos",
 *                 precio: 89,
 *                 precioSinImpuestos: 76.72,
 *                 impuesto1: 12.28,
 *                 impuesto2: 0,
 *                 impuesto3: 0,
 *                 descuento: 0,
 *                 bloqueado: false,
 *                 permitirprodcompenmodif: false
 *             }]
 *     }
 */
export interface CreateOrderRequest {
    licenseKey: string;
    "Idempotency-Key"?: string;
    turnDependent?: boolean;
    mesa?: string | null;
    idMesero?: string | null;
    estacion?: string | null;
    serie?: string | null;
    idEmpresa?: string | null;
    noPersonas?: number;
    productos?: WrestaurantApi.PartialProductDto[] | null;
}
