// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         licenseKey: "licenseKey"
 *     }
 */
export interface GetApiV1ProductosLicenseKeyRequest {
    licenseKey: string;
    page?: number;
    pageSize?: number;
    search?: string;
    idGrupo?: string;
    clasificacion?: string;
    visibleMenu?: boolean;
}
