// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         licenseKey: "licenseKey"
 *     }
 */
export interface GetEmpresasRequest {
    licenseKey: string;
}
