// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         licenseKey: "licenseKey",
 *         numCheque: 1
 *     }
 */
export interface GetFacturaXmlRequest {
    licenseKey: string;
    numCheque: number;
    idEmpresa?: string;
}
