// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         licenseKey: "licenseKey"
 *     }
 */
export interface GetOrderDetailsRequest {
    licenseKey: string;
    page?: number;
    pageSize?: number;
    folio?: number;
    search?: string;
}
