// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         licenseKey: "licenseKey"
 *     }
 */
export interface GetTempOrdersRequest {
    licenseKey: string;
    search?: string;
    page?: number;
    pageSize?: number;
    facturado?: boolean;
}
