// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         licenseKey: "licenseKey",
 *         idProducto: "idProducto"
 *     }
 */
export interface UpdateProductRequest {
    licenseKey: string;
    idProducto: string;
    "Idempotency-Key"?: string;
    idEmpresa?: string | null;
    descripcionProducto?: string | null;
    idGrupo?: string | null;
    nombreCorto?: string | null;
    visibleMenu?: boolean;
    precio?: number;
    impuesto1?: number;
    impuesto2?: number;
    impuesto3?: number;
    bloqueado?: boolean;
    permitirprodcompenmodif?: boolean;
}
