// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as WrestaurantApi from "../../../index.js";

export declare namespace EndpointsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class EndpointsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EndpointsClient.Options>;

    constructor(options: EndpointsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Devuelve el catálogo de productos de una sucursal, con paginación y filtros opcionales por grupo, clasificación y visibilidad en menú.
     *
     * @param {WrestaurantApi.GetProductsRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.getProducts({
     *         licenseKey: "licenseKey"
     *     })
     */
    public getProducts(
        request: WrestaurantApi.GetProductsRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.ProductsQueryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getProducts(request, requestOptions));
    }

    private async __getProducts(
        request: WrestaurantApi.GetProductsRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.ProductsQueryResponse>> {
        const { licenseKey, page, pageSize, search, idGrupo, clasificacion, visibleMenu } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
            search,
            idGrupo,
            clasificacion,
            visibleMenu,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/productos/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WrestaurantApi.ProductsQueryResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/productos/{licenseKey}",
        );
    }

    /**
     * Devuelve las estaciones (mesas, áreas, terminales) configuradas en una sucursal, con paginación y búsqueda opcional.
     *
     * @param {WrestaurantApi.GetStationsRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.getStations({
     *         licenseKey: "licenseKey"
     *     })
     */
    public getStations(
        request: WrestaurantApi.GetStationsRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.StationsQueryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getStations(request, requestOptions));
    }

    private async __getStations(
        request: WrestaurantApi.GetStationsRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.StationsQueryResponse>> {
        const { licenseKey, page, pageSize, search } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
            search,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/estaciones/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WrestaurantApi.StationsQueryResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/estaciones/{licenseKey}",
        );
    }

    /**
     * Devuelve las órdenes abiertas del Punto de Venta de una sucursal, con filtro opcional por folio, número de cheque o total.
     *
     * @param {WrestaurantApi.GetTempOrdersRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.getTempOrders({
     *         licenseKey: "licenseKey"
     *     })
     */
    public getTempOrders(
        request: WrestaurantApi.GetTempOrdersRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.OrdersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTempOrders(request, requestOptions));
    }

    private async __getTempOrders(
        request: WrestaurantApi.GetTempOrdersRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.OrdersResponse>> {
        const { licenseKey, search, page, pageSize } = request;
        const _queryParams: Record<string, unknown> = {
            search,
            page,
            pageSize,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/temp_ordenes/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WrestaurantApi.OrdersResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/temp_ordenes/{licenseKey}",
        );
    }

    /**
     * Crea una nueva cuenta y retorna el id.
     *
     * @param {WrestaurantApi.CreateOrderRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.BadRequestError}
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.createTempOrders({
     *         licenseKey: "licenseKey"
     *     })
     */
    public createTempOrders(
        request: WrestaurantApi.CreateOrderRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.CreateOrderResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createTempOrders(request, requestOptions));
    }

    private async __createTempOrders(
        request: WrestaurantApi.CreateOrderRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.CreateOrderResponse>> {
        const { licenseKey, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/temp_ordenes/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WrestaurantApi.CreateOrderResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new WrestaurantApi.BadRequestError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/temp_ordenes/{licenseKey}",
        );
    }

    /**
     * Crea una nueva venta cerrada con su pago y retorna el folio generado.
     *
     * @param {WrestaurantApi.CreateClosedOrderRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.BadRequestError}
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.createClosedTempOrder({
     *         licenseKey: "licenseKey"
     *     })
     */
    public createClosedTempOrder(
        request: WrestaurantApi.CreateClosedOrderRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.CreateClosedOrderResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createClosedTempOrder(request, requestOptions));
    }

    private async __createClosedTempOrder(
        request: WrestaurantApi.CreateClosedOrderRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.CreateClosedOrderResponse>> {
        const { licenseKey, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/temp_ordenes_cerradas/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as WrestaurantApi.CreateClosedOrderResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new WrestaurantApi.BadRequestError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v1/temp_ordenes_cerradas/{licenseKey}",
        );
    }

    /**
     * Devuelve el listado de meseros configurados en una sucursal.
     *
     * @param {WrestaurantApi.GetMeserosRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.getMeseros({
     *         licenseKey: "licenseKey"
     *     })
     */
    public getMeseros(
        request: WrestaurantApi.GetMeserosRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.MeserosResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getMeseros(request, requestOptions));
    }

    private async __getMeseros(
        request: WrestaurantApi.GetMeserosRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.MeserosResponse>> {
        const { licenseKey, search } = request;
        const _queryParams: Record<string, unknown> = {
            search,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/meseros/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WrestaurantApi.MeserosResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/meseros/{licenseKey}");
    }

    /**
     * Devuelve las empresas registradas en el Punto de Venta de una sucursal.
     *
     * @param {WrestaurantApi.GetEmpresasRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.getEmpresas({
     *         licenseKey: "licenseKey"
     *     })
     */
    public getEmpresas(
        request: WrestaurantApi.GetEmpresasRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.EmpresasResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getEmpresas(request, requestOptions));
    }

    private async __getEmpresas(
        request: WrestaurantApi.GetEmpresasRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.EmpresasResponse>> {
        const { licenseKey } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/empresas/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WrestaurantApi.EmpresasResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v1/empresas/{licenseKey}");
    }

    /**
     * Devuelve todas las cuentas activas (sin cancelar) del turno operativo actual (6:00 AM – 5:59:59 AM del día siguiente).
     *
     * @param {WrestaurantApi.GetOpenOrdersRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.getOpenOrders({
     *         licenseKey: "licenseKey"
     *     })
     */
    public getOpenOrders(
        request: WrestaurantApi.GetOpenOrdersRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.OpenOrdersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getOpenOrders(request, requestOptions));
    }

    private async __getOpenOrders(
        request: WrestaurantApi.GetOpenOrdersRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.OpenOrdersResponse>> {
        const { licenseKey } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/temp_ordenes_abiertas/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as WrestaurantApi.OpenOrdersResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/temp_ordenes_abiertas/{licenseKey}",
        );
    }

    /**
     * Devuelve las líneas de productos temporales de una sucursal, con paginación y filtros opcionales por folio de orden o búsqueda por producto.
     *
     * @param {WrestaurantApi.GetTempOrderDetailsRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.getTempOrderDetails({
     *         licenseKey: "licenseKey"
     *     })
     */
    public getTempOrderDetails(
        request: WrestaurantApi.GetTempOrderDetailsRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.OrderDetailsQueryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTempOrderDetails(request, requestOptions));
    }

    private async __getTempOrderDetails(
        request: WrestaurantApi.GetTempOrderDetailsRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.OrderDetailsQueryResponse>> {
        const { licenseKey, page, pageSize, folio, search } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
            folio,
            search,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/temp_ordenes_det/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as WrestaurantApi.OrderDetailsQueryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/temp_ordenes_det/{licenseKey}",
        );
    }

    /**
     * Retorna todas las formas de pago disponibles en una sucursal específica.
     *
     * @param {WrestaurantApi.GetPaymentMethodsRequest} request
     * @param {EndpointsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link WrestaurantApi.UnauthorizedError}
     * @throws {@link WrestaurantApi.NotFoundError}
     * @throws {@link WrestaurantApi.TooManyRequestsError}
     *
     * @example
     *     await client.endpoints.getPaymentMethods({
     *         licenseKey: "licenseKey"
     *     })
     */
    public getPaymentMethods(
        request: WrestaurantApi.GetPaymentMethodsRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): core.HttpResponsePromise<WrestaurantApi.PaymentMethodsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPaymentMethods(request, requestOptions));
    }

    private async __getPaymentMethods(
        request: WrestaurantApi.GetPaymentMethodsRequest,
        requestOptions?: EndpointsClient.RequestOptions,
    ): Promise<core.WithRawResponse<WrestaurantApi.PaymentMethodsResponse>> {
        const { licenseKey, page, pageSize, search } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            pageSize,
            search,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "X-Api-Key": requestOptions?.apiKey ?? this._options?.apiKey,
                "X-License-Key": requestOptions?.licenseKey ?? this._options?.licenseKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.WrestaurantApiEnvironment.Default,
                `api/v1/formasdepago/${core.url.encodePathParam(licenseKey)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as WrestaurantApi.PaymentMethodsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new WrestaurantApi.UnauthorizedError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 404:
                    throw new WrestaurantApi.NotFoundError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                case 429:
                    throw new WrestaurantApi.TooManyRequestsError(
                        _response.error.body as WrestaurantApi.ProblemDetails,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.WrestaurantApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v1/formasdepago/{licenseKey}",
        );
    }
}
