// This file was auto-generated by Fern from our API Definition.

import * as WrestaurantApi from "../../src/api/index";
import { WrestaurantApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("EndpointsClient", () => {
    test("listarProductos (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            jobId: "jobId",
            workerId: "workerId",
            dispatchedAt: "2024-01-15T09:30:00Z",
            page: 1,
            pageSize: 1,
            totalResults: 1,
            totalPages: 1,
            hasNextPage: true,
            products: [
                {
                    idProducto: "idProducto",
                    descripcionProducto: "descripcionProducto",
                    idGrupo: "idGrupo",
                    descripcionGrupo: "descripcionGrupo",
                    clasificacion: "clasificacion",
                    nombreCorto: "nombreCorto",
                    imagen: "imagen",
                    visibleMenu: true,
                    idProdServSat: "idProdServSat",
                    precio: 1.1,
                    impuesto1: 1.1,
                    impuesto2: 1.1,
                    impuesto3: 1.1,
                    bloqueado: true,
                    permitirprodcompenmodif: true,
                    modificadores: [{}],
                    gruposModificadores: [{}],
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/productos/licenseKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.listarProductos({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listarProductos (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/productos/licenseKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarProductos({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("listarProductos (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/productos/licenseKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarProductos({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("listarProductos (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/productos/licenseKey")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarProductos({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("listarEstaciones (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            jobId: "jobId",
            workerId: "workerId",
            dispatchedAt: "2024-01-15T09:30:00Z",
            page: 1,
            pageSize: 1,
            totalResults: 1,
            totalPages: 1,
            hasNextPage: true,
            stations: [
                {
                    idEstacion: "idEstacion",
                    descripcion: "descripcion",
                    serie: "serie",
                    ip: "ip",
                    impresoraCheques: "impresoraCheques",
                    impresoraNotas: "impresoraNotas",
                    cajaComandero: "cajaComandero",
                    directorioRespaldo: "directorioRespaldo",
                    rutaTemporal: "rutaTemporal",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/estaciones/licenseKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.listarEstaciones({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listarEstaciones (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/estaciones/licenseKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarEstaciones({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("listarEstaciones (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/estaciones/licenseKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarEstaciones({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("listarEstaciones (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/estaciones/licenseKey")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarEstaciones({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("listarOrdenesTemporales (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            workerId: "workerId",
            dispatchedAt: "2024-01-15T09:30:00Z",
            page: 1,
            pageSize: 1,
            totalResults: 1,
            totalPages: 1,
            hasNextPage: true,
            orders: [
                {
                    folio: 1,
                    serieFolio: "serieFolio",
                    numcheque: 1,
                    fecha: "2024-01-15T09:30:00Z",
                    cierre: "2024-01-15T09:30:00Z",
                    mesa: "mesa",
                    noPersonas: 1,
                    idMesero: "idMesero",
                    pagado: true,
                    cancelado: true,
                    impreso: true,
                    impresiones: 1,
                    descuento: 1.1,
                    razonCancelado: "razonCancelado",
                    orden: "orden",
                    facturado: true,
                    idTurno: 1,
                    usuarioCancelo: "usuarioCancelo",
                    comentarioDescuento: "comentarioDescuento",
                    usuarioPago: "usuarioPago",
                    totalArticulos: 1.1,
                    subtotal: 1.1,
                    subtotalSinImpuestos: 1.1,
                    total: 1.1,
                    totalConPropina: 1.1,
                    totalImpuestod1: 1.1,
                    totalImpuestod2: 1.1,
                    totalImpuestod3: 1.1,
                    efectivo: 1.1,
                    tarjeta: 1.1,
                    vales: 1.1,
                    otros: 1.1,
                    propina: 1.1,
                    totalSinDescuento: 1.1,
                    totalAlimentos: 1.1,
                    totalBebidas: 1.1,
                    totalOtros: 1.1,
                    totalDescuentos: 1.1,
                    totalCortesias: 1.1,
                    totalCortesiaAlimentos: 1.1,
                    items: [{}],
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes/licenseKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.listarOrdenesTemporales({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listarOrdenesTemporales (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes/licenseKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarOrdenesTemporales({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("listarOrdenesTemporales (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes/licenseKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarOrdenesTemporales({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("listarOrdenesTemporales (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes/licenseKey")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarOrdenesTemporales({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("crearUnaOrdenNuevaCuenta (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { jobId: "jobId", folio: 1 };

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.crearUnaOrdenNuevaCuenta({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("crearUnaOrdenNuevaCuenta (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.crearUnaOrdenNuevaCuenta({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.BadRequestError);
    });

    test("crearUnaOrdenNuevaCuenta (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.crearUnaOrdenNuevaCuenta({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("crearUnaOrdenNuevaCuenta (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.crearUnaOrdenNuevaCuenta({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("crearUnaOrdenNuevaCuenta (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.crearUnaOrdenNuevaCuenta({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("crearUnaOrdenCerradaVentaRapida (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { jobId: "jobId", folio: 1 };

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes_cerradas/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.crearUnaOrdenCerradaVentaRapida({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("crearUnaOrdenCerradaVentaRapida (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes_cerradas/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.crearUnaOrdenCerradaVentaRapida({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.BadRequestError);
    });

    test("crearUnaOrdenCerradaVentaRapida (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes_cerradas/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.crearUnaOrdenCerradaVentaRapida({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("crearUnaOrdenCerradaVentaRapida (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes_cerradas/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.crearUnaOrdenCerradaVentaRapida({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("crearUnaOrdenCerradaVentaRapida (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/temp_ordenes_cerradas/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.crearUnaOrdenCerradaVentaRapida({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("listarMeseros (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            workerId: "workerId",
            dispatchedAt: "2024-01-15T09:30:00Z",
            totalResults: 1,
            meseros: [
                {
                    idMeseroInterno: 1000000,
                    idMesero: "idMesero",
                    nombre: "nombre",
                    contrasena: "contrasena",
                    tipo: 1,
                    fotografia: "fotografia",
                    visible: true,
                    idEmpresa: "idEmpresa",
                    tipoAcceso: true,
                    capturaRestringidaMesas: true,
                    perfil: "perfil",
                    monitorMeseroColorFondo: 1.1,
                    monitorMeseroColorLetra: 1.1,
                    accesoIndicadorMesas: true,
                    turnoAbierto: true,
                    comision: 1.1,
                    autorizaProductosMenuQr: true,
                    workspaceId: "workspaceId",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/meseros/licenseKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.listarMeseros({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listarMeseros (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/meseros/licenseKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarMeseros({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("listarMeseros (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/meseros/licenseKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarMeseros({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("listarMeseros (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/meseros/licenseKey")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarMeseros({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("listarEmpresas (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            workerId: "workerId",
            dispatchedAt: "2024-01-15T09:30:00Z",
            totalResults: 1,
            empresas: [
                {
                    idEmpresa: "idEmpresa",
                    nombre: "nombre",
                    razonSocial: "razonSocial",
                    direccion: "direccion",
                    sucursal: "sucursal",
                    rfc: "rfc",
                    curp: "curp",
                    telefono: "telefono",
                    giro: "giro",
                    contacto: "contacto",
                    fax: "fax",
                    email: "email",
                    fechaCompra: "2024-01-15T09:30:00Z",
                    distribuidor: "distribuidor",
                    numeroFactura: "numeroFactura",
                    numeroDeControl: "numeroDeControl",
                    contrasenaControl: "contrasenaControl",
                    idHardware: "idHardware",
                    licenciaPrincipal: "licenciaPrincipal",
                    licenciaMonederoElectronico: "licenciaMonederoElectronico",
                    licenciaMonitorProduccion: "licenciaMonitorProduccion",
                    licenciaSrMovil: "licenciaSrMovil",
                    licenciaManttoVentas: "licenciaManttoVentas",
                    licenciaPagoEnLinea: "licenciaPagoEnLinea",
                    licenciaHuellaDigital: "licenciaHuellaDigital",
                    licenciaBillar: "licenciaBillar",
                    franquicia: "franquicia",
                    web: "web",
                    ciudad: "ciudad",
                    estado: "estado",
                    pais: "pais",
                    ciudadSucursal: "ciudadSucursal",
                    estadoSucursal: "estadoSucursal",
                    passwordEmpresa: "passwordEmpresa",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/empresas/licenseKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.listarEmpresas({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listarEmpresas (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/empresas/licenseKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarEmpresas({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("listarEmpresas (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/empresas/licenseKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarEmpresas({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("listarEmpresas (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/empresas/licenseKey")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarEmpresas({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("listarOrdenesAbiertasDelTurnoActual (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            workerId: "workerId",
            dispatchedAt: "2024-01-15T09:30:00Z",
            totalResults: 1,
            orders: [
                {
                    folio: 1,
                    serieFolio: "serieFolio",
                    numcheque: 1,
                    fecha: "2024-01-15T09:30:00Z",
                    cierre: "2024-01-15T09:30:00Z",
                    mesa: "mesa",
                    noPersonas: 1,
                    idMesero: "idMesero",
                    pagado: true,
                    cancelado: true,
                    impreso: true,
                    impresiones: 1,
                    descuento: 1.1,
                    razonCancelado: "razonCancelado",
                    orden: "orden",
                    facturado: true,
                    idTurno: 1,
                    usuarioCancelo: "usuarioCancelo",
                    comentarioDescuento: "comentarioDescuento",
                    usuarioPago: "usuarioPago",
                    totalArticulos: 1.1,
                    subtotal: 1.1,
                    subtotalSinImpuestos: 1.1,
                    total: 1.1,
                    totalConPropina: 1.1,
                    totalImpuestod1: 1.1,
                    totalImpuestod2: 1.1,
                    totalImpuestod3: 1.1,
                    efectivo: 1.1,
                    tarjeta: 1.1,
                    vales: 1.1,
                    otros: 1.1,
                    propina: 1.1,
                    totalSinDescuento: 1.1,
                    totalAlimentos: 1.1,
                    totalBebidas: 1.1,
                    totalOtros: 1.1,
                    totalDescuentos: 1.1,
                    totalCortesias: 1.1,
                    totalCortesiaAlimentos: 1.1,
                    nombreMesero: "nombreMesero",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes_abiertas/licenseKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.listarOrdenesAbiertasDelTurnoActual({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listarOrdenesAbiertasDelTurnoActual (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes_abiertas/licenseKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarOrdenesAbiertasDelTurnoActual({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("listarOrdenesAbiertasDelTurnoActual (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes_abiertas/licenseKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarOrdenesAbiertasDelTurnoActual({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("listarOrdenesAbiertasDelTurnoActual (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes_abiertas/licenseKey")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarOrdenesAbiertasDelTurnoActual({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("listarDetallesDeOrdenesTemporales (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            jobId: "jobId",
            workerId: "workerId",
            dispatchedAt: "2024-01-15T09:30:00Z",
            page: 1,
            pageSize: 1,
            totalResults: 1,
            totalPages: 1,
            hasNextPage: true,
            orderDetails: [
                {
                    folioDet: 1,
                    movimiento: 1,
                    comanda: "comanda",
                    cantidad: 1.1,
                    idProducto: "idProducto",
                    descuento: 1.1,
                    precio: 1.1,
                    precioSinImpuestos: 1.1,
                    comentario: "comentario",
                    tiempo: "2024-01-15T09:30:00Z",
                    mitad: 1.1,
                    hora: "2024-01-15T09:30:00Z",
                    modificador: 1,
                    idEstacion: "idEstacion",
                    impuesto1: 1.1,
                    impuesto2: 1.1,
                    impuesto3: 1.1,
                    usuarioDescuento: "usuarioDescuento",
                    comentarioDescuento: "comentarioDescuento",
                    idTipoDescuento: "idTipoDescuento",
                    idProductoCompuesto: "idProductoCompuesto",
                    productoCompuestoPrincipal: 1,
                    precioCatalogo: 1.1,
                    marcar: 1,
                    idMeseroProducto: "idMeseroProducto",
                    idCortesia: "idCortesia",
                    numeroTarjeta: "numeroTarjeta",
                    folioProduccion: 1.1,
                    nivel: 1,
                    sistemaEnvio: 1,
                    promoVolumen: 1,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes_det/licenseKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.listarDetallesDeOrdenesTemporales({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listarDetallesDeOrdenesTemporales (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes_det/licenseKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarDetallesDeOrdenesTemporales({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("listarDetallesDeOrdenesTemporales (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes_det/licenseKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarDetallesDeOrdenesTemporales({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("listarDetallesDeOrdenesTemporales (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/temp_ordenes_det/licenseKey")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarDetallesDeOrdenesTemporales({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("listarTodasLasFormasDePagoEnUnaSucursal (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            jobId: "jobId",
            workerId: "workerId",
            dispatchedAt: "2024-01-15T09:30:00Z",
            page: 1,
            pageSize: 1,
            totalResults: 1,
            totalPages: 1,
            hasNextPage: true,
            paymentMethods: [
                {
                    idFormaDePago: "idFormaDePago",
                    descripcion: "descripcion",
                    tipo: 1,
                    tipoDeCambio: 1.1,
                    solicitaReferencia: true,
                    prioridadBoton: 1,
                    cuentaContableImporte: "cuentaContableImporte",
                    cuentaContableComision: "cuentaContableComision",
                    cuentaContableIvaComision: "cuentaContableIvaComision",
                    comision: 1.1,
                    visible: true,
                    aceptaPropina: true,
                    subtipo: 1,
                    prefijo1: "prefijo1",
                    prefijo2: "prefijo2",
                    codigoDePrefijoconsulta: "codigoDePrefijoconsulta",
                    codigoDePrefijoacumred: "codigoDePrefijoacumred",
                    generaPuntos: true,
                    formatoImpresion: 1,
                    idFPagoFiscal: 1000000,
                    pagoEnLinea: 1,
                    tipoTarjeta: 1,
                    noFacturable: true,
                    comisionReporte1: 1.1,
                    comisionReporte2: 1.1,
                    tipoTarjetaBancaria: 1,
                    idTipoDescuento: "idTipoDescuento",
                    idFormaPagoSat: "idFormaPagoSat",
                    serviceCode: "serviceCode",
                    leerBrazalete: true,
                    cargoHabitacionEg: true,
                    visibleKiosco: true,
                    autocapturar: true,
                    sumaTotal: true,
                    equivalencia: "equivalencia",
                    bloqueaImporte: true,
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/formasdepago/licenseKey")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.endpoints.listarTodasLasFormasDePagoEnUnaSucursal({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listarTodasLasFormasDePagoEnUnaSucursal (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/formasdepago/licenseKey")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarTodasLasFormasDePagoEnUnaSucursal({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("listarTodasLasFormasDePagoEnUnaSucursal (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/formasdepago/licenseKey")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarTodasLasFormasDePagoEnUnaSucursal({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("listarTodasLasFormasDePagoEnUnaSucursal (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/formasdepago/licenseKey")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.endpoints.listarTodasLasFormasDePagoEnUnaSucursal({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });
});
