// This file was auto-generated by Fern from our API Definition.

import * as WrestaurantApi from "../../src/api/index";
import { WrestaurantApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ImpresorasClient", () => {
    test("ListPrinters (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = [
            {
                id: "id",
                workerId: "workerId",
                licenseKey: "licenseKey",
                printerIp: "printerIp",
                displayName: "displayName",
                widthMm: 1,
                source: "source",
                sourceId: "sourceId",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        ];

        server
            .mockEndpoint()
            .get("/api/v1/me/printers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.impresoras.listPrinters();
        expect(response).toEqual(rawResponseBody);
    });

    test("ListPrinters (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/me/printers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.listPrinters();
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("ListPrinters (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/me/printers")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.listPrinters();
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("CreatePrinter (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            licenseKey: "DS5D2368HCME4O9X",
            printerIp: "192.168.1.50",
            displayName: "Cocina",
            widthMm: 80,
            source: "windows",
            sourceId: "POS-01",
        };
        const rawResponseBody = {
            id: "id",
            workerId: "workerId",
            licenseKey: "licenseKey",
            printerIp: "printerIp",
            displayName: "displayName",
            widthMm: 1,
            source: "source",
            sourceId: "sourceId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/me/printers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.impresoras.createPrinter({
            licenseKey: "DS5D2368HCME4O9X",
            printerIp: "192.168.1.50",
            displayName: "Cocina",
            widthMm: 80,
            source: "windows",
            sourceId: "POS-01",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("CreatePrinter (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { licenseKey: null, printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/me/printers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.createPrinter({
                licenseKey: null,
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.BadRequestError);
    });

    test("CreatePrinter (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { licenseKey: null, printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/me/printers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.createPrinter({
                licenseKey: null,
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("CreatePrinter (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { licenseKey: null, printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/me/printers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.createPrinter({
                licenseKey: null,
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("CreatePrinter (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { licenseKey: null, printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/me/printers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.createPrinter({
                licenseKey: null,
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.ConflictError);
    });

    test("CreatePrinter (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { licenseKey: null, printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/me/printers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.createPrinter({
                licenseKey: null,
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("GetPrinter (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: "id",
            workerId: "workerId",
            licenseKey: "licenseKey",
            printerIp: "printerIp",
            displayName: "displayName",
            widthMm: 1,
            source: "source",
            sourceId: "sourceId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/me/printers/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.impresoras.getPrinter({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("GetPrinter (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/me/printers/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.getPrinter({
                id: "id",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("GetPrinter (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/me/printers/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.getPrinter({
                id: "id",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("GetPrinter (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/me/printers/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.getPrinter({
                id: "id",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("UpdatePrinter (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            printerIp: "192.168.1.51",
            displayName: "Cocina (caliente)",
            widthMm: 80,
            source: "windows",
            sourceId: "POS-01",
        };
        const rawResponseBody = {
            id: "id",
            workerId: "workerId",
            licenseKey: "licenseKey",
            printerIp: "printerIp",
            displayName: "displayName",
            widthMm: 1,
            source: "source",
            sourceId: "sourceId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .put("/api/v1/me/printers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.impresoras.updatePrinter({
            id: "id",
            printerIp: "192.168.1.51",
            displayName: "Cocina (caliente)",
            widthMm: 80,
            source: "windows",
            sourceId: "POS-01",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("UpdatePrinter (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/v1/me/printers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.updatePrinter({
                id: "id",
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.BadRequestError);
    });

    test("UpdatePrinter (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/v1/me/printers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.updatePrinter({
                id: "id",
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("UpdatePrinter (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/v1/me/printers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.updatePrinter({
                id: "id",
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("UpdatePrinter (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/v1/me/printers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.updatePrinter({
                id: "id",
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.ConflictError);
    });

    test("UpdatePrinter (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { printerIp: null, widthMm: 1 };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .put("/api/v1/me/printers/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.updatePrinter({
                id: "id",
                printerIp: null,
                widthMm: 1,
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("DeletePrinter (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        server.mockEndpoint().delete("/api/v1/me/printers/id").respondWith().statusCode(200).build();

        const response = await client.impresoras.deletePrinter({
            id: "id",
        });
        expect(response).toEqual(undefined);
    });

    test("DeletePrinter (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/me/printers/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.deletePrinter({
                id: "id",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("DeletePrinter (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/me/printers/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.deletePrinter({
                id: "id",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("DeletePrinter (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/api/v1/me/printers/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.deletePrinter({
                id: "id",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("PrintOrder (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            orderFolio: "169",
            isReprint: false,
            price: 128.5,
            paymentMethod: "CARD",
            businessName: "Mi Restaurante",
            businessSubtitle: "Sucursal Centro",
            groups: [
                {
                    printerId: "00000000-b12a-405f-905d-dbf424c20000",
                    jobType: "order",
                    title: "COCINA",
                    items: [
                        {
                            idProduct: "01052",
                            name: "Hamburguesa doble carne",
                            quantity: 2,
                            price: 89,
                            modifiers: [{ idModifier: "50110", name: "Sin cebolla", price: 0 }],
                            notes: "Sin pepinillos",
                        },
                    ],
                },
            ],
        };
        const rawResponseBody = {
            orderRef: "orderRef",
            results: [{ printerId: "printerId", jobId: "jobId", status: "status", error: "error" }],
        };

        server
            .mockEndpoint()
            .post("/api/v1/print/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.impresoras.printOrder({
            licenseKey: "licenseKey",
            orderFolio: "169",
            isReprint: false,
            price: 128.5,
            paymentMethod: "CARD",
            businessName: "Mi Restaurante",
            businessSubtitle: "Sucursal Centro",
            groups: [
                {
                    printerId: "00000000-b12a-405f-905d-dbf424c20000",
                    jobType: "order",
                    title: "COCINA",
                    items: [
                        {
                            idProduct: "01052",
                            name: "Hamburguesa doble carne",
                            quantity: 2,
                            price: 89,
                            modifiers: [
                                {
                                    idModifier: "50110",
                                    name: "Sin cebolla",
                                    price: 0,
                                },
                            ],
                            notes: "Sin pepinillos",
                        },
                    ],
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("PrintOrder (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderFolio: null, isReprint: true, groups: null };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/print/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.printOrder({
                licenseKey: "licenseKey",
                orderFolio: null,
                isReprint: true,
                groups: null,
            });
        }).rejects.toThrow(WrestaurantApi.BadRequestError);
    });

    test("PrintOrder (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderFolio: null, isReprint: true, groups: null };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/print/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.printOrder({
                licenseKey: "licenseKey",
                orderFolio: null,
                isReprint: true,
                groups: null,
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("PrintOrder (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderFolio: null, isReprint: true, groups: null };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/print/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.printOrder({
                licenseKey: "licenseKey",
                orderFolio: null,
                isReprint: true,
                groups: null,
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("PrintOrder (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { orderFolio: null, isReprint: true, groups: null };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/print/licenseKey")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.printOrder({
                licenseKey: "licenseKey",
                orderFolio: null,
                isReprint: true,
                groups: null,
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });

    test("GetPrinters (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            workerId: "workerId",
            printers: [{ id: "id", printerIp: "printerIp", displayName: "displayName", widthMm: 1, source: "source" }],
        };

        server
            .mockEndpoint()
            .get("/api/v1/print/licenseKey/printers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.impresoras.getPrinters({
            licenseKey: "licenseKey",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("GetPrinters (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/print/licenseKey/printers")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.getPrinters({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.UnauthorizedError);
    });

    test("GetPrinters (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/print/licenseKey/printers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.getPrinters({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.NotFoundError);
    });

    test("GetPrinters (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new WrestaurantApiClient({
            maxRetries: 0,
            apiKey: "test",
            licenseKey: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/print/licenseKey/printers")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.impresoras.getPrinters({
                licenseKey: "licenseKey",
            });
        }).rejects.toThrow(WrestaurantApi.TooManyRequestsError);
    });
});
