// This file was auto-generated by Fern from our API Definition.

export const WrestaurantApiEnvironment = {
    Default: "https://api.wrestaurantapi.com",
} as const;

export type WrestaurantApiEnvironment = typeof WrestaurantApiEnvironment.Default;
